### PR TITLE
Add CircleCI script

### PR DESCRIPTION
**Pull request by izgzhen**

### CODE REVIEW

**Comment by izgzhen** [comment]
To enable this, @snowleopard you need to add hadrian project in CircleCI's panel, it will by default use a Linux bot to build so will fail, but it is okay. I will then write an email to the support to enable the OS X Seed Plan for you.

**Comment by izgzhen** [comment]
Also, you can create a new branch for testing this, if then I will change to merge into that branch instead.

**Comment by snowleopard** [comment]
@izgzhen I've registered at CircleCI and am about to add Hadrian project. There are four options: OS can be Linux or OSX, and "platform" can be 1.0 (classic) or 2.0 (new). 

Shall I go for Linux 2.0?

**Comment by izgzhen** [comment]
> Shall I go for Linux 2.0?

I think you can try this first.

**Comment by snowleopard** [comment]
@izgzhen Done. Something is being built!

**Comment by snowleopard** [comment]
https://circleci.com/gh/snowleopard/hadrian/1

**Comment by izgzhen** [comment]
Great, I will get back to you when they enable the OS X seed plan for your build.

**Comment by snowleopard** [comment]
Right, I've readded the project as an OSX one and merged this PR. Let's see if it works.

**Comment by snowleopard** [comment]
It works, thanks @izgzhen! We now have a new OS X badge: https://github.com/snowleopard/hadrian

**Pull request merged**
