### PR TITLE
Drop GccLtXX flags, require GCC > 4.7 and up

### PR DESCRIPTION
**Pull request by izgzhen**
See https://github.com/snowleopard/hadrian/issues/449.

### CODE REVIEW

**Comment by snowleopard** [comment]
@izgzhen Thanks for the patch!

Looks like you haven't removed all uses of the flags, so CI Hadrian can't be compiled.

**Comment by izgzhen** [comment]
> Looks like you haven't removed all uses of the flags, so Hadrian can't be compiled.

Yes! I was in a hurry at the time of making this PR, sorry.

**Comment by snowleopard** [comment]
We now hit GHC panic:
```
Stderr:
ghc: panic! (the 'impossible' happened)
  (GHC version 8.0.2 for x86_64-unknown-mingw32):
	tcIfaceGlobal (local): not found
  You are in a maze of twisty little passages, all alike.
  While forcing the thunk for TyThing SyntaxExpr
  which was lazily initialized by initIfaceTcRn,
  I tried to tie the knot, but I couldn't find SyntaxExpr
  in the current type environment.
  If you are developing GHC, please read Note [Tying the knot]
  and Note [Type-checking inside the knot].
  Consider rebuilding GHC with profiling for a better stack trace.
  Contents of current type environment: []
Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
)
```
:-S Presumably GHC is broken? Or did we break it by a strange combination of flags?

**Comment by snowleopard** [comment]
Ah, wait, this is bootstrapping GHC! So, it's a real bug which we somehow triggered by flags.

**Comment by izgzhen** [comment]
> Ah, wait, this is bootstrapping GHC! So, it's a real bug which we somehow triggered by flags.

O_o interesting

**Comment by snowleopard** [comment]
@izgzhen One possible explanation is that this GHC commit: 

https://github.com/ghc/ghc/commit/0ff152c9e633accca48815e26e59d1af1fe44ceb

Changed `compiler/hsSyn/HsExpr.hs` in such a way that it started to trigger an old GHC bug. It's therefore not the fault of this PR.

**Comment by snowleopard** [comment]
OK, I've confirmed this. GHC appears to be currently broken on 8.0.2.

@bgamari Shall I report this or is this a known issue?

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> OK, I've confirmed this. GHC appears to be currently broken on 8.0.2.
>
> @bgamari Shall I report this or is this a known issue?
>
No need, I'm working with @alanz on it.

**Pull request merged**
