### PR TITLE
Add validate flavour

### PR DESCRIPTION
**Pull request by izgzhen**
Implement https://github.com/ghc/ghc/blob/464396d00450efb58330987ebac4735902ba0f01/mk/flavours/validate.mk#L1-L11.

@snowleopard Can you help me double check if this translation is right?

### CODE REVIEW

**Comment by snowleopard** [comment]
@izgzhen Thanks! This looks fine. Does it reduce the number of validation failures even further?

Do we run Hadrian with both `validate` and `--flavour=validate`? It looks a bit awkward. Perhaps, the `validate` target should switch the default flavour from `default` to `validate`? This is quite similar to the documentation build rule, where we need to run Hadrian with `docs` target and flag `--haddock`, see #414.

Please also update `doc/flavours.md`.

**Comment by izgzhen** [comment]
From version built with `validate` flavor from #422 

```
SUMMARY for test run started at Sat Sep 30 10:44:00 2017 HKT
 0:14:04 spent to go through
    6109 total tests, which gave rise to
   24013 test cases, of which
   17962 were skipped

      43 had missing libraries
    5786 expected passes
      91 expected failures

       0 caused framework failures
       0 caused framework warnings
       0 unexpected passes
     129 unexpected failures
       2 unexpected stat failures

Unexpected failures:
   annotations/should_compile/th/annth_make.run       annth_make [bad stdout] (normal)
   annotations/should_compile/th/annth_compunits.run  annth_compunits [bad stdout] (normal)
   cabal/ghcpkg05.run                                 ghcpkg05 [bad stderr] (normal)
   codeGen/should_run/T10414.run                      T10414 [exit code non-0] (threaded2)
   concurrent/should_run/conc069.run                  conc069 [bad exit code] (ghci)
   concurrent/should_run/conc069a.run                 conc069a [bad exit code] (ghci)
   concurrent/should_run/conc070.run                  conc070 [bad stdout] (ghci)
   concurrent/should_run/conc072.run                  conc072 [exit code non-0] (threaded2)
   concurrent/should_run/numsparks001.run             numsparks001 [exit code non-0] (threaded1)
   concurrent/should_run/T3429.run                    T3429 [exit code non-0] (debug_numa)
   concurrent/should_run/T5558.run                    T5558 [exit code non-0] (threaded2)
   dynlibs/T3807.run                                  T3807 [bad exit code] (normal)
   ffi/should_run/ffi014.run                          ffi014 [exit code non-0] (threaded1)
   ffi/should_run/Capi_Ctype_001.run                  Capi_Ctype_001 [bad exit code] (normal)
   ffi/should_run/Capi_Ctype_002.run                  Capi_Ctype_002 [bad exit code] (normal)
   hsc2hs/hsc2hs001.run                               hsc2hs001 [bad exit code] (normal)
   hsc2hs/hsc2hs002.run                               hsc2hs002 [bad exit code] (normal)
   hsc2hs/hsc2hs003.run                               hsc2hs003 [bad exit code] (normal)
   hsc2hs/hsc2hs004.run                               hsc2hs004 [bad exit code] (normal)
   hsc2hs/T3837.run                                   T3837 [bad exit code] (normal)
   hsc2hs/T4340.run                                   T4340 [bad exit code] (normal)
   hsc2hs/T10272.run                                  T10272 [bad exit code] (normal)
   hsc2hs/T12504.run                                  T12504 [bad exit code] (normal)
   plugins/frontend01.run                             frontend01 [bad stdout] (normal)
   printer/Ppr001.run                                 Ppr001 [bad exit code] (normal)
   printer/Ppr002.run                                 Ppr002 [bad exit code] (normal)
   printer/Ppr003.run                                 Ppr003 [bad exit code] (normal)
   printer/Ppr004.run                                 Ppr004 [bad exit code] (normal)
   printer/Ppr005.run                                 Ppr005 [bad exit code] (normal)
   printer/Ppr006.run                                 Ppr006 [bad exit code] (normal)
   printer/Ppr007.run                                 Ppr007 [bad exit code] (normal)
   printer/Ppr008.run                                 Ppr008 [bad exit code] (normal)
   printer/Ppr009.run                                 Ppr009 [bad exit code] (normal)
   printer/Ppr010.run                                 Ppr010 [bad exit code] (normal)
   printer/Ppr011.run                                 Ppr011 [bad exit code] (normal)
   printer/Ppr012.run                                 Ppr012 [bad exit code] (normal)
   printer/Ppr013.run                                 Ppr013 [bad exit code] (normal)
   printer/Ppr014.run                                 Ppr014 [bad exit code] (normal)
   printer/Ppr015.run                                 Ppr015 [bad exit code] (normal)
   printer/Ppr016.run                                 Ppr016 [bad exit code] (normal)
   printer/Ppr017.run                                 Ppr017 [bad exit code] (normal)
   printer/Ppr018.run                                 Ppr018 [bad exit code] (normal)
   printer/Ppr019.run                                 Ppr019 [bad exit code] (normal)
   printer/Ppr020.run                                 Ppr020 [bad exit code] (normal)
   printer/Ppr021.run                                 Ppr021 [bad exit code] (normal)
   printer/Ppr022.run                                 Ppr022 [bad exit code] (normal)
   printer/Ppr023.run                                 Ppr023 [bad exit code] (normal)
   printer/Ppr024.run                                 Ppr024 [bad exit code] (normal)
   printer/Ppr025.run                                 Ppr025 [bad exit code] (normal)
   printer/Ppr026.run                                 Ppr026 [bad exit code] (normal)
   printer/Ppr027.run                                 Ppr027 [bad exit code] (normal)
   printer/Ppr028.run                                 Ppr028 [bad exit code] (normal)
   printer/Ppr029.run                                 Ppr029 [bad exit code] (normal)
   printer/Ppr030.run                                 Ppr030 [bad exit code] (normal)
   printer/Ppr031.run                                 Ppr031 [bad exit code] (normal)
   printer/Ppr032.run                                 Ppr032 [bad exit code] (normal)
   printer/Ppr033.run                                 Ppr033 [bad exit code] (normal)
   printer/Ppr034.run                                 Ppr034 [bad exit code] (normal)
   printer/Ppr035.run                                 Ppr035 [bad exit code] (normal)
   printer/Ppr036.run                                 Ppr036 [bad exit code] (normal)
   printer/Ppr037.run                                 Ppr037 [bad exit code] (normal)
   printer/Ppr038.run                                 Ppr038 [bad exit code] (normal)
   printer/Ppr039.run                                 Ppr039 [bad exit code] (normal)
   printer/Ppr040.run                                 Ppr040 [bad exit code] (normal)
   printer/Ppr041.run                                 Ppr041 [bad exit code] (normal)
   printer/Ppr042.run                                 Ppr042 [bad exit code] (normal)
   printer/Ppr043.run                                 Ppr043 [bad exit code] (normal)
   printer/Ppr044.run                                 Ppr044 [bad exit code] (normal)
   printer/Ppr045.run                                 Ppr045 [bad exit code] (normal)
   printer/Ppr046.run                                 Ppr046 [bad exit code] (normal)
   printer/Ppr048.run                                 Ppr048 [bad exit code] (normal)
   printer/T13199.run                                 T13199 [bad exit code] (normal)
   printer/T13050p.run                                T13050p [bad exit code] (normal)
   printer/T13550.run                                 T13550 [bad exit code] (normal)
   printer/T13942.run                                 T13942 [bad exit code] (normal)
   profiling/should_run/T3001-2.run                   T3001-2 [exit code non-0] (prof_hb)
   profiling/should_run/scc003.run                    scc003 [bad profile] (profasm)
   profiling/should_run/scc001.run                    scc001 [bad exit code] (ghci-ext-prof)
   profiling/should_run/scc002.run                    scc002 [bad exit code] (ghci-ext-prof)
   profiling/should_run/scc003.run                    scc003 [bad profile] (prof)
   profiling/should_run/scc003.run                    scc003 [bad exit code] (ghci-ext-prof)
   profiling/should_run/scc005.run                    scc005 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T680.run                      T680 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T2552.run                     T2552 [bad exit code] (ghci-ext-prof)
   profiling/should_run/prof-doc-fib.run              prof-doc-fib [bad exit code] (ghci-ext-prof)
   profiling/should_run/prof-doc-last.run             prof-doc-last [bad exit code] (ghci-ext-prof)
   profiling/should_run/T5559.run                     T5559 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (profasm)
   profiling/should_run/profinline001.run             profinline001 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (prof_hc_hb)
   profiling/should_run/T5363.run                     T5363 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (prof_hb)
   profiling/should_run/T12962.run                    T12962 [bad profile] (profasm)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (prof_hd)
   profiling/should_run/T12962.run                    T12962 [bad profile] (prof)
   profiling/should_run/T12962.run                    T12962 [bad exit code] (ghci-ext-prof)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (prof_hy)
   quasiquotation/T14028.run                          T14028 [bad stderr] (normal)
   profiling/should_run/T11627b.run                   T11627b [bad heap profile] (prof_hr)
   rts/testwsdeque.run                                testwsdeque [exit code non-0] (threaded1)
   rts/atomicxchg.run                                 atomicxchg [exit code non-0] (threaded1)
   rts/T4850.run                                      T4850 [bad exit code] (normal)
   rts/ffishutdown.run                                ffishutdown [exit code non-0] (threaded1)
   rts/T8209.run                                      T8209 [bad stderr] (ghci)
   rts/T8242.run                                      T8242 [bad stderr] (ghci)
   rts/T8124.run                                      T8124 [exit code non-0] (threaded1)
   rts/T9078.run                                      T9078 [exit code non-0] (threaded1)
   rts/linker_error1.run                              linker_error1 [bad exit code] (normal)
   rts/linker_error2.run                              linker_error2 [bad exit code] (normal)
   rts/linker_error3.run                              linker_error3 [bad exit code] (normal)
   rts/T10728.run                                     T10728 [exit code non-0] (threaded2)
   rts/T10296b.run                                    T10296b [exit code non-0] (threaded2)
   rts/numa001.run                                    numa001 [exit code non-0] (debug_numa)
   runghc/T7859.run                                   T7859 [bad stderr] (normal)
   runghc/T8601.run                                   T8601 [bad stderr] (normal)
   th/TH_spliceE5_prof_ext.run                        TH_spliceE5_prof_ext [bad exit code] (normal)
   th/TH_spliceE5_prof.run                            TH_spliceE5_prof [bad exit code] (normal)
   th/TH_linker/path_with_commas.run                  path_with_commas [bad exit code] (normal)
   typecheck/T13168/T13168.run                        T13168 [bad stderr] (normal)
   typecheck/should_compile/T11462.run                T11462 [exit code non-0] (normal)
   typecheck/should_compile/T11525.run                T11525 [exit code non-0] (normal)
   ../../libraries/base/tests/CPUTime001.run          CPUTime001 [bad stdout] (normal)
   ../../libraries/base/tests/IO/T12010/T12010.run    T12010 [bad exit code] (threaded1)
   ../../libraries/process/tests/T3231.run            T3231 [exit code non-0] (threaded1)
   ../../libraries/process/tests/T3994.run            T3994 [exit code non-0] (threaded1)
   ../../libraries/stm/tests/stm056.run               stm056 [exit code non-0] (threaded1)
   ../../libraries/unix/tests/forkprocess01.run       forkprocess01 [exit code non-0] (threaded1_ls)
   ../../libraries/unix/tests/fdReadBuf001.run        fdReadBuf001 [bad exit code] (ghci)
   rts/T7815.run                                      T7815 [exit code non-0] (threaded1)

Unexpected stat failures:
   perf/compiler/T5837.run   T5837 [stat too good] (normal)
   perf/compiler/T12150.run  T12150 [stat too good] (optasm)
```

It is neither a subset or a super set of the previous log as in #299. Interesting.

**Comment by snowleopard** [comment]
> It is neither a subset or a super set of the previous log as in #299. Interesting.

Strange, this flavour even makes things worse?

**Comment by izgzhen** [comment]
> Strange, this flavour even makes things worse?

Hard to say. It fixed some errors, while revealing some more others. I need a closer inspection.

**Comment by izgzhen** [comment]
See #299

**Pull request closed without merging**
