### PR TITLE
Rearrange unix build scripts.

### PR DESCRIPTION
**Pull request by duog**
Addresses Issue #428 

This isn't identifying the renames properly, sorry about that.

build.stack.nix.sh delegates to build.stack.sh with an environment variable, this seemed simpler than trying to work out how to use getopts.

### CODE REVIEW

**Comment by snowleopard** [comment]
@duog Thank you, looks good! Can you also update the Travis and CircleCI scripts to use `build.sh`?

**Comment by duog** [comment]
Build scripts updated

**Comment by snowleopard** [comment]
Thanks @duog! Looks good to me, so I'm merging.

**Comment by duog** [comment]
Sorry about that botched renaming :/

**Comment by snowleopard** [comment]
@duog No problem, I missed this too!

**Pull request merged**
