### PR TITLE
.travis.yml: update OS X script to test a GHC patch for #614

### PR DESCRIPTION
**Pull request by alpmestan**
I'm hoping to see the OS X travis job go green... =)

### CODE REVIEW

**Comment by snowleopard** [comment]
@alpmestan I'm afraid I already tried the `#if defined(DEBUG)` trick -- and it doesn't work. We don't process Cabal files with CPP.

**Comment by snowleopard** [comment]
There are also a couple of relevant comments here: https://phabricator.haskell.org/D4846

**Comment by alpmestan** [comment]
Oh, I'll just go with the "always defined" direction suggested in the diff. Thanks! I'll update this branch once this is done.

**Comment by snowleopard** [comment]
Thanks @alpmestan!

**Comment by alpmestan** [comment]
I pushed an updated patch in my GHC branch ([here](https://github.com/alpmestan/ghc/commit/43b9cc0d9b3efc9036862b19f1c157129c45ea8c)) and relaunched the OS X build on travis: https://travis-ci.org/snowleopard/hadrian/jobs/425273841

**Comment by snowleopard** [comment]
@alpmestan Cool! Can you do the same with the CircleCI script?

**Comment by alpmestan** [comment]
In the meantime, I opened a diff for the GHC patch: https://phabricator.haskell.org/D5138

**Comment by alpmestan** [comment]
Done.

**Comment by snowleopard** [comment]
@alpmestan Thanks! Yes, I'll merge once CircleCI completes.

Sorry, I somehow missed your question. We are building Haddock and `ghctags` in Stage2 now, because this is what Make does. See this issue: #661.

**Comment by alpmestan** [comment]
https://github.com/snowleopard/hadrian/pull/690

**Pull request merged**
