### PR TITLE
Fix validate's hsc2hs dependency (#375)

### PR DESCRIPTION
**Pull request by izgzhen**

### CODE REVIEW

**Comment by izgzhen** [comment]
Sorry for that but it looks like `needBuilder Hsc2Hs`, ultimately, doesn't work on my machine. I should really check it carefully before submitting last PR. sigh.

**Comment by snowleopard** [comment]
@izgzhen Strange, the previous PR passed all CI. Anyway, merging this one.

**Comment by izgzhen** [comment]
> the previous PR passed all CI

It is just that `validate` can't execute, which our CI doesn't check.

**Comment by snowleopard** [comment]
Ah, indeed. Thanks!

**Pull request merged**
