### PR TITLE
Use --depth 1 for git clone

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks @gracjan!

Presumably, this could be done with AppVeyor CI too -- could you add a similar fix to `appveyor.yml`?

**Comment by gracjan** [comment]
Does not work. git is limited.

There is 54 sec to save, so this might be useful provided we can make this work.

**Comment by snowleopard** [comment]
> Does not work. git is limited.

@gracjan Could you please clarify? Do you mean `--depth 1` doesn't work on Windows?

**Comment by snowleopard** [comment]
Note that some time ago we actually had `--depth 1` in Travis: https://github.com/snowleopard/hadrian/commit/c43d07d967b7a7876e6a7733a343934d35d0d616

Somehow this got lost later (my fault).

**Comment by gracjan** [comment]
It fails on TravisCI:

```
$ git clone --depth 1 --recursive git://git.haskell.org/ghc.git --quiet
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

`--depth 1` does not go well toghether with `--recursive`, looks like old git limitation/bug.

**Comment by gracjan** [comment]
Hmm, `--depth ` does not work at all:

```
$ git clone git://git.haskell.org/ghc.git --depth 1 --quiet
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

What git is running on `git://git.haskell.org/ghc.git`? Is this a potentially old version that somehow does not support `--depth 1`?

**Comment by gracjan** [comment]
Looks like github is not a perfect mirror of submodules and is missing stuff:

```
Fetched in submodule path 'libffi-tarballs', but it did not contain ec37a68838566cb830c33cb30bfade003a306cff. Direct fetching of that commit failed.
```

**Comment by gracjan** [comment]
So this change removes 30sek from build time. Well, not much. Learnings so far:

1. Travis has git 1.8.5.6 on Linux and 2.10.0 on Mac. The first one does not support `--shallow-modules`.
2. `git://git.haskell.org/ghc.git` does not support `--depth 1` on server side.
3. `--shallow-modules` fails for some modules on github mirror. Potentially bad mirroring.

Way forward:
1. Ask guys for newer git on `git://git.haskell.org/ghc.git`. Revert from github mirror to cannonical source.
2. Install newer git client on Linux Travis
3. Add `--shallow-modules` option.

Anyway this PR is ready to be merged, giving 30 sek shorter build times.

**Comment by snowleopard** [comment]
@gracjan Many thanks for thorough investigation! This is now merged.

**Comment by ndmitchell** [comment]
Getting The Haskell.org git upgraded probably isn't hard.

**Comment by snowleopard** [comment]
@ndmitchell How do we do that? Is raising an issue at https://github.com/haskell-infra/hl the right way to go?

**Comment by ndmitchell** [comment]
Seems a reasonable first step - at least they should be able to point you in a better direction.

**Comment by snowleopard** [comment]
@ndmitchell Thanks, done: https://github.com/haskell-infra/hl/issues/202.

**Pull request merged**
