### PR TITLE
Various improvements to the Stack build.

### PR DESCRIPTION
**Pull request by mboes**
Have a look at the list of commits for details.

### CODE REVIEW

**Comment by snowleopard** [comment]
Many thanks @mboes!

Looks like this breaks the Windows CI: 

https://ci.appveyor.com/project/snowleopard/hadrian/build/1.0.432

Perhaps, we need to modify `appveyor.yml` to adapt to your `alex`/`happy` changes? If yes, does this mean we need to change this doc too: https://github.com/snowleopard/hadrian/blob/master/doc/windows.md?

Regarding the switch to LTS-8.21: please have a look at PR #292. Could you share your thoughts there?

**Comment by mboes** [comment]
Could it be that earlier builds on Windows happened a while ago and therefore picked up an earlier version of Stack? I can't see anything in my PR that would cause the `alex` / `happy` problem to appear if it hadn't already been there. Maybe switching to a more recent LTS triggers it, but I'm skeptical. Either that or previous builds used a build cache primed with the right build tools and that cache expired maybe.

> Perhaps, we need to modify appveyor.yml to adapt to your alex/happy changes?

Yes, and I've just pushed a tentative change to that. But then we also need to change the docs, and then also `./build.stack.bat`. Could be perhaps have `appveyor.yaml` just call out to the latter to avoid triplicating the fix?

**Comment by snowleopard** [comment]
> Could it be that earlier builds on Windows happened a while ago and therefore picked up an earlier version of Stack? 

I don't think so: look at #334, which has just built successfully after the failed build here.

> Could be perhaps have `appveyor.yaml` just call out to the latter to avoid triplicating the fix?

Good idea! It would be nice to make it work and reduce code duplication.

**Comment by snowleopard** [comment]
Btw, I think you missed a `-` in front of `stack build alex happy`.

**Comment by snowleopard** [comment]
@mboes Hey, we are ready to bump the LTS version, but it looks like the Stack's issue has been resolved meanwhile, so the workaround (installing Alex and Happy directly) is no longer required.

Would you like to remove the workaround from this PR, or shall I simply close this, and:
* Bump the LTS version
* Incorporate your changes to `stack.yaml` that remove the boilerplate and add `nix` stuff?

**Comment by izgzhen** [comment]
@snowleopard I think we can bump the version safely now. since @mboes is not responsive, I guess you can fix it directly.

@mboes still a lot of thanks though

**Comment by snowleopard** [comment]
@izgzhen Agreed, I'll do this today and will close the PR.

**Comment by snowleopard** [comment]
Done.

**Pull request closed without merging**
