### PR TITLE
Make OS X build faster and Add GHC 8.0.2 build on Travis CI

### PR DESCRIPTION
**Pull request by izgzhen**
Related: #322, #292

### CODE REVIEW

**Comment by izgzhen** [comment]
Looks like Travis CI OS X can't afford a full build, even if we use ghc 8.0.2 https://travis-ci.org/izgzhen/hadrian/jobs/255095240

**Comment by izgzhen** [comment]
Updated, now it is a 7.10.3 Linux + 8.0.2 Linux + 7.10.3 OS X (stage1) combo

**Comment by snowleopard** [comment]
Great, thanks! Will merge it once it goes through.

**Comment by snowleopard** [comment]
OS X finished pretty quickly! 

https://travis-ci.org/snowleopard/hadrian/builds/255238071?utm_source=github_status&utm_medium=notification

@izgzhen Do you know if we could somehow make it visible on the above page which GHC is used for the two Linux instances? Then if one of them fails, one could easily which version is broken. Perhaps, we could do this by adding a dummy variable "GHC=7.10.3" and "GHC=8.0.2"?

**Comment by izgzhen** [comment]
I can let this page display the version info (https://travis-ci.org/snowleopard/hadrian/builds/255282296) together, but not on badge. I checked several other projects, it looks like there is no way to make a fancier badge.

**Comment by snowleopard** [comment]
> I can let this page display the version info together, by adding a compiler:

That's perfect, thanks! I've merged this.

**Pull request merged**
