### PR TITLE
Add Werror to CC and HC

### PR DESCRIPTION
**Pull request by izgzhen**
Related: https://github.com/snowleopard/hadrian/issues/296

### CODE REVIEW

**Comment by snowleopard** [comment]
@izgzhen Thank you! 

This currently fails on AppVeyor:
```
Stderr:
rts/StgCRun.c: In function 'win32AllocStack':
rts/StgCRun.c:109:12: error: function returns address of local variable [-Werror=return-local-addr]
     return stack;
            ^~~~~
cc1.exe: all warnings being treated as errors
```

**Comment by izgzhen** [comment]
Thanks, I never intend to solve it at one shot :)

I will keep pushing stuff and observe how CI complains (but it was refine on my macOS machine).

**Comment by izgzhen** [comment]
> This currently fails on AppVeyor:

@snowleopard I can't find anything about `return-local-addr` warning in the old make-based system. Should we ignore this warning somehow, or maybe seek help from someone familiar this?

**Comment by izgzhen** [comment]
@snowleopard also, Linux build failed with unexpected timeout, maybe you can try to restart it?

**Comment by snowleopard** [comment]
> I can't find anything about return-local-addr warning in the old make-based system. 

@izgzhen Yes, this is strange. We could try adding something like `-Wreturn-local-addr` at least temporary, but I wonder why the Make build system doesn't need it.

> also, macOS build failed with unexpected timeout, maybe you can try to restart it?

I've restarted the MacOS build, but sadly it rarely completes within the time limit (seems to be just a little over the limit).

**Comment by izgzhen** [comment]
I pushed some changes addressing `-Wreturn-local-addr` and also the `WARNING_OPTS`

**Comment by snowleopard** [comment]
AppVeyor still unhappy.

**Comment by izgzhen** [comment]
Oh, my bad, I guess it would be `-Wno-return-local-addr`

**Comment by izgzhen** [comment]
AppVeyor is happy now ;)

**Comment by snowleopard** [comment]
Looks good! :) Shall I merge?

**Comment by izgzhen** [comment]
Yes, feel free to merge it

**Comment by snowleopard** [comment]
@izgzhen Thanks!

**Pull request merged**
