### PR TITLE
Enable optional UserSettings.hs file

### LINKED ISSUE #247: Do not check src/Settings/User.hs into the repository
Any changes a user of Hadrian makes to that file should not get included into their GHC commits (by accident).

Possible solution:
* `git mv src/Settings/User.hs src/Settings/DefaultUser.hs` 
* In `build.sh`, if `src/Settings/User.hs` is missing, either abort or show a warning and `cp src/Settings/DefaultUser.hs src/Settings/User.hs`.

Checking out old revisions of Hadrian will cause some problems though.

### PR DESCRIPTION
**Pull request by KaiHa**
Fix #247

The defaul user settings are stored in ./src/UserSettings.hs. If the
user want to override these settings, he can copy this file into ./ and
make the desired changes to ./UserSettings.hs.

### CODE REVIEW

**Comment by snowleopard** [comment]
Great, thanks!

The only thing to discuss: do we want users to copy `src/UserSettings.hs` or, as also mentioned previously, rename `./UserSettings.hs.sample`? The latter may be more familiar, as users currently rename `build.mk.sample`. The sample file may actually differ from `src/UserSettings.hs` and contain several common settings commented out.

**Comment by snowleopard** [comment]
@KaiHa @ndmitchell @thomie @Ericson2314 Any thoughts on the above comment?

**Comment by KaiHa** [comment]
> The only thing to discuss: do we want users to copy src/UserSettings.hs or, as also mentioned previously, rename ./UserSettings.hs.sample?

Both approaches are fine for me.

**Comment by Ericson2314** [comment]
If I understand correctly, this uses the precedence of '.' over 'src/' to work?

**Comment by KaiHa** [comment]
> If I understand correctly, this uses the precedence of '.' over 'src/' to work?

Correct

**Comment by Ericson2314** [comment]
Anything with `.sample` would be more complex then. My vote is for this. Good work!

**Comment by ndmitchell** [comment]
Looks very good to me. Thanks @KaiHa.

**Comment by snowleopard** [comment]
OK, merged as is. Thanks again!

**Pull request merged**
