### PR TITLE
Ghc cabal

### PR DESCRIPTION
**Pull request by angerman**
This should bring us towards fixing #18! :tada:

### CODE REVIEW

**Comment by snowleopard** [comment]
I've removed `ghc-cabal` package (woo-hoo!) and added support for `hp2ps`. Everything looks very nice compared to the previous stringy mess. Let's see how far I can go today!

**Comment by snowleopard** [comment]
This is taking longer than expected, so I am thinking that we might have to postpone it until a later milestone. @angerman Do you agree?

**Comment by angerman** [comment]
@snowleopard Yes. I think we tried to byte of a bit too much to chew.

**Comment by angerman** [comment]
I don't think this is going anywhere. Let's shave this yak some other time.

**Comment by snowleopard** [comment]
@angerman Yes, this turned out to be quite a bit more complicated than we hoped to. Anyway, thank you and @bgamari for the efforts!

**Comment by snowleopard** [comment]
I think we should also delete the `ghc-cabal` branch. It's badly out of date and is likely to confuse people.

**Pull request closed without merging**
