### PR TITLE
Add dependency on the new "llvm-passes" file.

### PR DESCRIPTION
**Pull request by kavon**
This change updates Hadrian for an upcoming revision to GHC.

For details, see https://phabricator.haskell.org/D4695

### CODE REVIEW

**Comment by snowleopard** [comment]
@kavon Thank you! This looks good to me but fails on CI since the file `llvm-passes` is still missing. I guess we should wait until `D4695` has landed.

**Comment by snowleopard** [comment]
@kavon OK, fine :) Our CI bots are broken anyway, so I've merged!

**Comment by angerman** [comment]
Current GHC HEAD is broken for a few days, and I believe @bgamari has an open merge queue for things to merge once the build is green again.

**Comment by snowleopard** [comment]
Thanks @angerman, I see.

**Pull request merged**
